from pathlib import Path

class FileAgent:
    def create_project(self, name):
        project = Path(name)

        project.mkdir(parents=True, exist_ok=True)

        files = {
            "README.md": f"# {name}\n\nGenerated by AK-Engine\n",
            "requirements.txt": "",
            "main.py": f'print("Welcome to {name}")\n',
        }

        created = []

        for filename, content in files.items():
            path = project / filename
            path.write_text(content, encoding="utf-8")
            created.append(str(path))

        return created
