import json
import re
import shutil
import tempfile
from ak_engine.core.context import AgentContext
from ak_engine.core.execution_state import ExecutionState
from ak_engine.smart_router import SmartRouter

from ak_engine.agents.planner_agent import PlannerAgent
from ak_engine.agents.coding_agent import CodingAgent
from ak_engine.agents.runner_agent import RunnerAgent
from ak_engine.agents.debugger_agent import DebuggerAgent
from ak_engine.agents.file_agent import FileAgent
from ak_engine.agents.terminal_agent import TerminalAgent
from ak_engine.agents.git_agent import GitAgent
from ak_engine.agents.memory_agent import MemoryAgent
from ak_engine.agents.input_agent import InputAgent
from ak_engine.agents.validator_agent import ValidatorAgent
from ak_engine.agents.tool_agent import ToolAgent
from ak_engine.agents.research_agent import ResearchAgent
from ak_engine.agents.project_agent import ProjectAgent
from ak_engine.agents.test_engine import TestEngine
from ak_engine.memory.learning_memory import LearningMemory


from pathlib import Path
class Orchestrator:

    def __init__(self):

        self.context = AgentContext()
        self.state = ExecutionState()
        self.router = SmartRouter()

        self.planner = PlannerAgent()
        self.coder = CodingAgent()
        self.runner = RunnerAgent()
        self.debugger = DebuggerAgent()
        self.files = FileAgent()
        self.terminal = TerminalAgent()
        self.git = GitAgent()
        self.memory = MemoryAgent()
        self.learning = LearningMemory()
        self.input_agent = InputAgent()
        self.validator = ValidatorAgent()
        self.tool = ToolAgent()
        self.research = ResearchAgent()
        self.project = ProjectAgent()
        self.test_engine = TestEngine()


    def _collect_project_files(self, project_root="generated_project"):
        """
        Collect Python source files from the generated project.

        Generated bytecode/cache files are intentionally excluded.
        """
        root = Path(project_root)

        if not root.exists():
            return {}

        files = {}

        for path in sorted(root.rglob("*.py")):
            if "__pycache__" in path.parts:
                continue

            relative = path.relative_to(root).as_posix()

            try:
                files[relative] = path.read_text(
                    encoding="utf-8"
                )
            except (OSError, UnicodeDecodeError):
                continue

        return files

    def _parse_project_repair(self, reply):
        """
        Robustly parse and validate a JSON project-repair response.

        The debugger may wrap JSON in markdown fences or add short
        explanatory text. The parser extracts the first valid JSON
        object while keeping strict repair-schema validation.
        """
        if not isinstance(reply, str):
            raise ValueError(
                "Project repair response must be text."
            )

        cleaned = reply.strip()

        if not cleaned:
            raise ValueError(
                "Debugger returned an empty project repair response."
            )

        # Remove common markdown fences without assuming the entire
        # response is only JSON.
        cleaned = re.sub(
            r"^\s*```(?:json)?\s*",
            "",
            cleaned,
            flags=re.IGNORECASE,
        )

        cleaned = re.sub(
            r"\s*```\s*$",
            "",
            cleaned,
            flags=re.IGNORECASE,
        ).strip()

        decoder = json.JSONDecoder()
        data = None
        last_error = None

        # First try the complete response.
        try:
            data, _ = decoder.raw_decode(cleaned)
        except json.JSONDecodeError as exc:
            last_error = exc

            # Then scan for the first valid JSON object.
            for index, char in enumerate(cleaned):
                if char != "{":
                    continue

                try:
                    candidate, _ = decoder.raw_decode(
                        cleaned[index:]
                    )
                    if isinstance(candidate, dict):
                        data = candidate
                        break
                except json.JSONDecodeError as exc:
                    last_error = exc

        if data is None:
            if last_error:
                raise ValueError(
                    "Debugger did not return a valid JSON repair object: "
                    f"{last_error}"
                ) from last_error

            raise ValueError(
                "Debugger did not return a valid JSON repair object."
            )

        if not isinstance(data, dict):
            raise ValueError(
                "Project repair must be a JSON object."
            )

        files = data.get("files")

        if not isinstance(files, list):
            raise ValueError(
                "Project repair must contain a files list."
            )

        for index, item in enumerate(files):
            if not isinstance(item, dict):
                raise ValueError(
                    f"Repair file #{index + 1} must be an object."
                )

            path = item.get("path")
            content = item.get("content")

            if not isinstance(path, str):
                raise ValueError(
                    f"Repair file #{index + 1} path must be a string."
                )

            if not path.strip():
                raise ValueError(
                    f"Repair file #{index + 1} path cannot be empty."
                )

            if not isinstance(content, str):
                raise ValueError(
                    f"Repair file #{index + 1} content must be a string."
                )

        reason = data.get("reason", "")

        if reason is not None and not isinstance(reason, str):
            raise ValueError(
                "Project repair reason must be a string."
            )

        return data

    def _apply_project_repair(
        self,
        repair,
        project_root="generated_project",
    ):
        """
        Safely apply only the files returned by the project debugger.
        """
        root = Path(project_root).resolve()

        changed = []

        for item in repair.get("files", []):
            relative = Path(item["path"])

            if relative.is_absolute():
                raise ValueError(
                    f"Absolute repair path rejected: {item['path']}"
                )

            target = (root / relative).resolve()

            if not (
                target == root
                or str(target).startswith(str(root) + "/")
            ):
                raise ValueError(
                    f"Unsafe repair path rejected: {item['path']}"
                )

            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(
                item["content"],
                encoding="utf-8",
            )

            changed.append(relative.as_posix())

        return changed

    def _snapshot_project(self, project_root="generated_project"):
        """
        Create a filesystem snapshot before autonomous healing.

        The snapshot is isolated from the working project and excludes
        Python bytecode/cache files.
        """
        root = Path(project_root)

        if not root.exists():
            raise FileNotFoundError(
                f"Project root does not exist: {project_root}"
            )

        snapshot = Path(
            tempfile.mkdtemp(prefix="ak_engine_heal_")
        )

        shutil.copytree(
            root,
            snapshot,
            dirs_exist_ok=True,
            ignore=shutil.ignore_patterns(
                "__pycache__",
                "*.pyc",
                "*.pyo",
            ),
        )

        return str(snapshot)

    def _restore_project(
        self,
        snapshot,
        project_root="generated_project",
    ):
        """
        Restore the project from a healing snapshot.
        """
        root = Path(project_root)
        backup = Path(snapshot)

        if not backup.exists():
            raise FileNotFoundError(
                f"Healing snapshot does not exist: {snapshot}"
            )

        if root.exists():
            shutil.rmtree(root)

        shutil.copytree(
            backup,
            root,
            dirs_exist_ok=True,
        )

    def _discard_snapshot(self, snapshot):
        """
        Remove a completed healing snapshot.
        """
        if not snapshot:
            return

        path = Path(snapshot)

        if path.exists():
            shutil.rmtree(path)

    def _heal_project(
        self,
        goal,
        filename,
        sample_input,
        result,
        packages,
        max_attempts=2,
        project_root="generated_project",
    ):
        """
        Transactional project-level autonomous healing.

        Every repair is applied inside a snapshot transaction.
        The deterministic TestEngine decides whether the repair
        actually worked.
        """

        entrypoint = Path(filename).name

        for heal_attempt in range(1, max_attempts + 1):

            print(
                f"\\n[Project Healing] "
                f"Attempt {heal_attempt}/{max_attempts}"
            )

            snapshot = None

            try:
                snapshot = self._snapshot_project(project_root)

                files = self._collect_project_files(project_root)

                verification = result.get("verification")

                error_context = result.get("stderr", "")

                if verification:
                    error_context = (
                        "DETERMINISTIC VERIFICATION FAILED\\n\\n"
                        f"Failed checks: "
                        f"{verification.get('failed_reasons', [])}\\n\\n"
                        "Verification evidence:\\n"
                        f"{verification}\\n\\n"
                        "Program stdout:\\n"
                        + result.get("stdout", "")
                        + "\\n\\nProgram stderr:\\n"
                        + result.get("stderr", "")
                    )

                print("[Project Healing] Asking repair agent...")

                reply = self.debugger.fix_project(
                    files=files,
                    entrypoint=entrypoint,
                    error=error_context,
                    verification=verification,
                )

                repair = self._parse_project_repair(reply)

                changed = self._apply_project_repair(
                    repair,
                    project_root=project_root,
                )

                print(
                    "[Project Healing] Changed files:",
                    changed
                )

                if not changed:
                    raise ValueError(
                        "Repair agent returned no files to modify."
                    )

                # Compile every repaired Python source before execution.
                compile_errors = []

                for relative in changed:
                    if not relative.endswith(".py"):
                        continue

                    target = Path(project_root) / relative

                    try:
                        compile(
                            target.read_text(encoding="utf-8"),
                            str(target),
                            "exec",
                        )
                    except SyntaxError as exc:
                        compile_errors.append(
                            f"{relative}: {exc}"
                        )

                if compile_errors:
                    raise RuntimeError(
                        "Repaired project contains syntax errors: "
                        + "; ".join(compile_errors)
                    )

                print("[Project Healing] Compilation passed.")

                healed_result = self.runner.run_python(
                    filename,
                    user_input=sample_input,
                )

                healed_evidence = self._verify_runtime(
                    goal,
                    sample_input,
                    healed_result,
                )

                if healed_evidence is not None:

                    if healed_evidence.get("passed"):

                        print(
                            "🔥 [Project Healing] "
                            "Deterministic verification PASSED."
                        )

                        self._discard_snapshot(snapshot)

                        healed_result["verification"] = healed_evidence

                        self.learning.remember(
                            goal,
                            packages,
                            True,
                        )

                        return healed_result

                    print(
                        "❌ [Project Healing] "
                        "Deterministic verification FAILED."
                    )

                    healed_result["verification"] = healed_evidence

                else:
                    # Non-calculator projects still use the existing validator.
                    if healed_result.get("success") and self.validator.validate(
                        goal,
                        self.files.read_file(filename),
                        healed_result.get("stdout", ""),
                    ):
                        print(
                            "🔥 [Project Healing] "
                            "LLM validator accepted repaired project."
                        )

                        self._discard_snapshot(snapshot)

                        self.learning.remember(
                            goal,
                            packages,
                            True,
                        )

                        return healed_result

                print("[Project Healing] Rolling back failed repair.")

                self._restore_project(
                    snapshot,
                    project_root=project_root,
                )

                self._discard_snapshot(snapshot)
                snapshot = None

                # Continue with another project-level repair attempt.
                result = healed_result

            except Exception as exc:

                print(
                    "[Project Healing] ERROR:",
                    type(exc).__name__,
                    exc,
                )

                if snapshot:
                    try:
                        self._restore_project(
                    snapshot,
                    project_root=project_root,
                )
                        print(
                            "↩️ [Project Healing] "
                            "Project restored from snapshot."
                        )
                    finally:
                        self._discard_snapshot(snapshot)

        print(
            "❌ [Project Healing] "
            "All project-level healing attempts failed."
        )

        return None

    def _verify_runtime(self, goal, sample_input, result):
        """
        Deterministic runtime verification.

        TestEngine is currently strongest for interactive calculator-style
        programs. Other project types continue through the existing
        LLM validator until their contracts are implemented.
        """
        if "calculator" not in goal.lower():
            return None

        evidence = self.test_engine.inspect_output(
            sample_input,
            result.get("stdout", ""),
            result.get("stderr", ""),
            result.get("returncode", -1),
        )

        summary = self.test_engine.summarize(evidence)

        print("\n[Verification Evidence]")

        for check in evidence.get("checks", []):
            mark = "✅" if check.get("passed") else "❌"
            print(f"{mark} {check.get('name')}")

        print(
            f"Verification: "
            f"{summary['passed_checks']}/{summary['total_checks']} checks passed"
        )

        if not summary["passed"]:
            print(
                "[Verification Failure] "
                + ", ".join(summary["failed_reasons"])
            )

        return evidence

    def execute(self, goal):
        """
        Execute one autonomous AK Engine project lifecycle.

        ExecutionState is the canonical lifecycle record for this run.
        """

        print(f"\n🎯 Goal: {goal}\n")

        # ---------------------------------------------------------
        # INITIALIZE EXECUTION STATE
        # ---------------------------------------------------------

        self.state = ExecutionState()

        self.state.goal = goal

        route = self.router.route_details(goal)

        self.state.task = route["task"]
        self.state.set_phase("routing")

        self.context.set("task", self.state.task)
        self.context.set("routing", route)

        print(
            f"[Router] Task: {route['task']} "
            f"-> {route['primary']}"
        )

        # ---------------------------------------------------------
        # MEMORY
        # ---------------------------------------------------------

        self.memory.remember("last_goal", goal)

        # ---------------------------------------------------------
        # RESEARCH
        # ---------------------------------------------------------

        self.state.set_phase("research")

        print("[Research]")

        try:
            research = self.research.research(goal)
            self.state.research = research
            self.context.set("research", research)

            print(research)

        except Exception as exc:
            self.state.add_error(exc)
            self.state.fail()
            print(f"❌ Research failed: {exc}")
            return self.state.snapshot()

        # ---------------------------------------------------------
        # LEARNING MEMORY
        # ---------------------------------------------------------

        self.state.set_phase("memory")

        print("\n[Learning Memory]")

        try:
            memories = self.learning.search(goal)
            self.state.memories = memories

            memory_text = "\n".join(
                str(x) for x in memories
            )

            print(
                memory_text
                if memory_text
                else "No similar projects."
            )

        except Exception as exc:
            self.state.add_error(exc)
            memories = []
            self.state.memories = []
            memory_text = ""

            print(f"⚠️ Learning memory unavailable: {exc}")

        # ---------------------------------------------------------
        # PLANNING
        # ---------------------------------------------------------

        self.state.set_phase("planning")

        print("\n[Planner]")

        try:
            plan = self.planner.plan(goal)

            self.state.plan = plan
            self.context.set("plan", plan)

            for step in plan:
                print(step)

        except Exception as exc:
            self.state.add_error(exc)
            self.state.fail()
            print(f"❌ Planning failed: {exc}")
            return self.state.snapshot()

        # ---------------------------------------------------------
        # DEPENDENCY / TOOL ANALYSIS
        # ---------------------------------------------------------

        self.state.set_phase("dependencies")

        print("\n[Tool Agent]")

        try:
            packages = self.tool.detect_packages(goal)

            self.state.packages = packages
            self.context.set("packages", packages)

            print(packages)

            if packages:
                self.tool.install_many(packages)

        except Exception as exc:
            self.state.add_error(exc)
            self.state.fail()
            print(f"❌ Dependency stage failed: {exc}")
            return self.state.snapshot()

        # ---------------------------------------------------------
        # PROJECT GENERATION
        # ---------------------------------------------------------

        self.state.set_phase("generation")

        print("\n[Project Agent]")

        try:
            project = self.project.generate(
                goal,
                research,
                memory_text,
                "\n".join(packages),
            )

            filename = self.project.write_project(project)

            project_root = str(
                Path(filename).resolve().parent
            )

            self.state.project = project
            self.state.project_root = project_root
            self.state.entrypoint = project["entrypoint"]

            self.context.set("project", project)
            self.context.set("project_root", project_root)

            print(
                f"Generated project: {filename}"
            )

            for file in project["files"]:
                print(
                    f"  ├── {file['path']}"
                )

        except Exception as exc:
            self.state.add_error(exc)
            self.state.fail()
            print(f"❌ Project generation failed: {exc}")
            return self.state.snapshot()

        # ---------------------------------------------------------
        # EXECUTION / VERIFICATION LOOP
        # ---------------------------------------------------------

        for attempt in range(1, 4):

            self.state.set_phase("execution")
            self.state.attempts = attempt

            print(
                f"\n========== Attempt {attempt} ==========\n"
            )

            try:
                code = self.files.read_file(filename)

                print("[Input Agent]")

                sample_input = self.input_agent.generate(
                    goal,
                    code,
                )

                self.state.sample_input = sample_input
                self.context.set(
                    "sample_input",
                    sample_input,
                )

                print(sample_input)

                print("\n[Runner]")

                lines = [
                    line.strip()
                    for line in sample_input.splitlines()
                    if line.strip()
                ]

                has_prompt_text = any(
                    "enter " in line.lower()
                    or "choose " in line.lower()
                    or "input " in line.lower()
                    for line in lines
                )

                has_numbered_menu = sum(
                    1
                    for line in lines
                    if line.strip() in {
                        "1", "2", "3", "4", "5",
                        "6", "7", "8", "9", "0",
                    }
                ) >= 2

                cli_commands = {
                    "add", "list", "create", "search",
                    "delete", "complete", "update",
                    "remove", "show", "edit",
                    "quit", "exit",
                }

                cli_like_lines = [
                    line
                    for line in lines
                    if line.split()
                    and line.split()[0].lower()
                    in cli_commands
                    and (
                        len(line.split()) == 1
                        or "-" in line
                        or "=" in line
                    )
                ]

                cli_mode = (
                    bool(lines)
                    and not has_prompt_text
                    and not has_numbered_menu
                    and len(cli_like_lines) >= 1
                )

                if cli_mode:

                    print(
                        "[Runner] Mode: CLI commands"
                    )

                    combined_stdout = []
                    combined_stderr = []
                    last_result = None

                    for command in lines:

                        print(
                            f"[Runner] $ python "
                            f"{filename} {command}"
                        )

                        result = self.runner.run_python(
                            filename,
                            args=command,
                        )

                        last_result = result

                        if result["stdout"]:
                            print(result["stdout"])
                            combined_stdout.append(
                                result["stdout"]
                            )

                        if result["stderr"]:
                            print(result["stderr"])
                            combined_stderr.append(
                                result["stderr"]
                            )

                    if last_result is None:

                        result = {
                            "success": False,
                            "stdout": "",
                            "stderr": (
                                "No CLI commands were generated."
                            ),
                            "stage": "runner",
                        }

                    else:

                        result = dict(last_result)

                        result["stdout"] = (
                            "\n".join(combined_stdout)
                        )

                        result["stderr"] = (
                            "\n".join(combined_stderr)
                        )

                else:

                    print(
                        "[Runner] Mode: interactive stdin"
                    )

                    result = self.runner.run_python(
                        filename,
                        user_input=sample_input,
                    )

                    print(result["stdout"])

                    if result["stderr"]:
                        print(result["stderr"])

                self.state.execution_result = result
                self.context.set(
                    "execution_result",
                    result,
                )

                # -------------------------------------------------
                # SUCCESSFUL PROCESS
                # -------------------------------------------------

                if result["success"]:

                    print(result["stdout"])

                    evidence = self._verify_runtime(
                        goal,
                        sample_input,
                        result,
                    )

                    self.state.verification = evidence

                    if evidence is not None:

                        if evidence["passed"]:

                            self.state.validation_passed = True
                            self.state.succeed()

                            self.learning.remember(
                                goal,
                                packages,
                                True,
                            )

                            print(
                                "🔥 Execution completed successfully."
                            )

                            return self.state.snapshot()

                        print(
                            "❌ Deterministic verification failed."
                        )

                        result["verification"] = evidence

                    else:

                        print("\n[Validator]")

                        valid = self.validator.validate(
                            goal,
                            code,
                            result["stdout"],
                        )

                        self.state.validation_passed = valid

                        if valid:

                            print(
                                "✅ Goal validated successfully."
                            )

                            self.state.succeed()

                            self.learning.remember(
                                goal,
                                packages,
                                True,
                            )

                            return self.state.snapshot()

                        print(
                            "❌ Validator rejected project."
                        )

                else:

                    print(result["stderr"])

                # -------------------------------------------------
                # AUTONOMOUS HEALING
                # -------------------------------------------------

                self.state.set_phase("healing")

                print("\n[Project Healing]")

                healed_result = self._heal_project(
                    goal=goal,
                    filename=filename,
                    sample_input=sample_input,
                    result=result,
                    packages=packages,
                    max_attempts=2,
                    project_root=project_root,
                )

                if healed_result is not None:

                    self.state.execution_result = healed_result

                    if healed_result.get(
                        "verification"
                    ):
                        self.state.verification = (
                            healed_result["verification"]
                        )

                    self.state.add_repair({
                        "attempt": attempt,
                        "status": "successful",
                    })

                    self.state.validation_passed = True
                    self.state.succeed()

                    print(
                        "🔥 Project healed successfully."
                    )

                    return self.state.snapshot()

                print(
                    "❌ Project-level healing failed."
                )

                print(
                    "↩️ No unverified repair was kept."
                )

                self.state.add_error(
                    f"Execution attempt {attempt} failed."
                )

                break

            except Exception as exc:

                self.state.add_error(exc)

                print(
                    f"❌ Execution attempt {attempt} "
                    f"raised an exception: {exc}"
                )

                break

        # ---------------------------------------------------------
        # FINAL FAILURE
        # ---------------------------------------------------------

        self.state.fail()

        self.learning.remember(
            goal,
            packages,
            False,
        )

        print(
            "\n❌ AK Engine execution failed."
        )

        return self.state.snapshot()
